site_name: 洛谷题目浏览站
repo_url: https://github.com/CB-X2-Jun/luogu-problem-reader
nav:
  - 首页: index.md
  - 题目列表: problem/list.md
  - 关于: about.md
theme: 
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true