[build]
  # 发布目录 - Netlify将从这个目录部署文件
  publish = "."
  
  # Functions目录
  functions = "netlify/functions"

[build.environment]
  # 可以在这里设置构建时的环境变量
  NODE_VERSION = "18"

# 重定向规则
[[redirects]]
  # 处理SPA路由 (如果需要的话)
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Headers配置
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# 为API函数设置CORS
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
