# 洛谷题目浏览站 - 静态部署到 GitHub Pages
name: Deploy Luogu Problem Reader to Pages

on:
  # 推送到主分支时触发
  push:
    branches: ["main"]
  
  # 允许手动触发
  workflow_dispatch:

# GitHub Pages 部署权限
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许一个并发部署
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 静态文件部署任务
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        
      - name: 配置 GitHub Pages
        uses: actions/configure-pages@v5
        
      - name: 清理不必要的文件
        run: |
          # 删除Python相关文件和目录，避免Jekyll处理问题
          rm -rf venv/ __pycache__/ *.py *.pyc
          rm -f requirements.txt
          # 保留.nojekyll文件确保禁用Jekyll
          echo "清理完成，保留静态文件"
          ls -la
        
      - name: 上传静态文件
        uses: actions/upload-pages-artifact@v3
        with:
          # 上传整个目录，但已清理Python文件
          path: '.'
          
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
